/**
 * Content QA Rules & Pillars Configuration
 * 
 * Centralized, configuration-driven rule definitions for all 12 QA Pillars.
 * Defines weights, failure severities, applicable platforms, scopes, and automation flags.
 * Allows rules to be configured, enabled, or weighted without rewriting engine code.
 */

export const QA_PILLARS_CONFIG = {
  tone_style_ai: {
    id: 'tone_style_ai',
    number: 1,
    label: 'Tone, Style, and AI Check',
    iconKey: 'sparkles',
    color: '#3B82F6',
    description: 'Human voice, natural cadence, zero robotic AI phrases, and clean punctuation.',
    targetWeight: 1.0,
  },
  read_aloud: {
    id: 'read_aloud',
    number: 2,
    label: 'Read Aloud Test',
    iconKey: 'volume',
    color: '#8B5CF6',
    description: 'Auditory naturalness, rhythmic flow, and verbal scannability when spoken.',
    targetWeight: 1.0,
  },
  audience_alignment: {
    id: 'audience_alignment',
    number: 3,
    label: 'Audience Alignment',
    iconKey: 'users',
    color: '#EC4899',
    description: 'Unified persona targeting, search intent fulfillment, and attention-holding focus.',
    targetWeight: 1.0,
  },
  eeat_check: {
    id: 'eeat_check',
    number: 4,
    label: 'E‑E‑A‑T Check',
    iconKey: 'award',
    color: '#F59E0B',
    description: 'Observable evidence, lived experience, underlying why/how, and thought-leadership.',
    targetWeight: 1.0,
  },
  insight_first: {
    id: 'insight_first',
    number: 5,
    label: 'Insight First',
    iconKey: 'zap',
    color: '#10B981',
    description: 'Opening directly with a punchy hook or observation instead of long throat-clearing setup.',
    targetWeight: 1.0,
  },
  meaning_crispness: {
    id: 'meaning_crispness',
    number: 6,
    label: 'Meaning & Crispness Test',
    iconKey: 'scissors',
    color: '#06B6D4',
    description: 'Every line earns its place with new perspective, value, and zero filler sentences.',
    targetWeight: 1.0,
  },
  zero_offensiveness: {
    id: 'zero_offensiveness',
    number: 7,
    label: 'Zero Offensiveness Rule',
    iconKey: 'shield-check',
    color: '#6366F1',
    description: 'Professional, respectful framing that does not undermine professions, industries, or competitors.',
    targetWeight: 0.8,
  },
  brand_positioning: {
    id: 'brand_positioning',
    number: 8,
    label: 'Relevance to Brand Positioning',
    iconKey: 'compass',
    color: '#D97706',
    description: 'Alignment with verified brand voice, reinforcing authority without sounding salesy.',
    targetWeight: 1.0,
  },
  structure_check: {
    id: 'structure_check',
    number: 9,
    label: 'Structure Check',
    iconKey: 'layout',
    color: '#14B8A6',
    description: 'Strong headline, relevant supporting subline, logical narrative flow, and clean tense.',
    targetWeight: 1.0,
  },
  no_direct_sales_pitches: {
    id: 'no_direct_sales_pitches',
    number: 10,
    label: 'No Direct Sales Pitches',
    iconKey: 'ban',
    color: '#EF4444',
    description: 'Crisp storytelling without hype, aggressive self-promotion, or milestone bragging.',
    targetWeight: 1.2,
  },
  compliance_risk: {
    id: 'compliance_risk',
    number: 11,
    label: 'Compliance & Risk Check',
    iconKey: 'alert-triangle',
    color: '#F97316',
    description: 'Zero unverified claims across regulated domains (health, medical, finance, legal, safety).',
    targetWeight: 1.4,
  },
  visual_platform_fit: {
    id: 'visual_platform_fit',
    number: 12,
    label: 'Visual + Platform Fit',
    iconKey: 'monitor',
    color: '#84CC16',
    description: 'Platform length fit, scannability (paragraphs, lists), and visual media recommendations.',
    targetWeight: 1.0,
  },
}

export const QA_RULES_CATALOG = [
  // ── Pillar 1: Tone, Style, and AI Check ────────────────────────
  {
    ruleId: 'ts-1',
    pillarId: 'tone_style_ai',
    label: 'Is the tone human, crisp, and conversational?',
    weight: 1.2,
    severityOnFailure: 'medium',
    applicablePlatforms: ['all'],
    applicableContentTypes: ['all'],
    scope: ['prose'],
    isAutomated: true,
    isInformational: false,
    defaultStatus: 'PASS',
  },
  {
    ruleId: 'ts-2',
    pillarId: 'tone_style_ai',
    label: 'No robotic phrases, no fluff, no clichés.',
    weight: 1.5,
    severityOnFailure: 'high',
    applicablePlatforms: ['all'],
    applicableContentTypes: ['all'],
    scope: ['prose', 'headings'],
    isAutomated: true,
    isInformational: false,
    defaultStatus: 'PASS',
  },
  {
    ruleId: 'ts-3',
    pillarId: 'tone_style_ai',
    label: 'No em dashes in editorial prose.',
    weight: 1.5,
    severityOnFailure: 'high',
    applicablePlatforms: ['all'],
    applicableContentTypes: ['all'],
    scope: ['prose', 'headings'],
    isAutomated: true,
    isInformational: false,
    defaultStatus: 'PASS',
  },
  {
    ruleId: 'ts-5',
    pillarId: 'tone_style_ai',
    label: 'No colons in editorial prose.',
    weight: 1.5,
    severityOnFailure: 'high',
    applicablePlatforms: ['all'],
    applicableContentTypes: ['all'],
    scope: ['prose', 'headings'],
    isAutomated: true,
    isInformational: false,
    defaultStatus: 'PASS',
  },
  {
    ruleId: 'ts-4',
    pillarId: 'tone_style_ai',
    label: 'Sentences clear, complete, not abrupt.',
    weight: 1.0,
    severityOnFailure: 'medium',
    applicablePlatforms: ['all'],
    applicableContentTypes: ['all'],
    scope: ['prose'],
    isAutomated: true,
    isInformational: false,
    defaultStatus: 'PASS',
  },

  // ── Pillar 2: Read Aloud Test ───────────────────────────────────
  {
    ruleId: 'ra-1',
    pillarId: 'read_aloud',
    label: 'If read out loud, does it sound natural?',
    weight: 1.2,
    severityOnFailure: 'medium',
    applicablePlatforms: ['all'],
    applicableContentTypes: ['all'],
    scope: ['prose'],
    isAutomated: true,
    isInformational: false,
    defaultStatus: 'PASS',
  },
  {
    ruleId: 'ra-2',
    pillarId: 'read_aloud',
    label: 'Does it hold attention, sound confident, and flow smoothly?',
    weight: 1.0,
    severityOnFailure: 'low',
    applicablePlatforms: ['all'],
    applicableContentTypes: ['all'],
    scope: ['prose'],
    isAutomated: false,
    isInformational: false,
    defaultStatus: 'MANUAL_REVIEW',
  },
  {
    ruleId: 'ra-3',
    pillarId: 'read_aloud',
    label: 'Can any line be shortened without losing meaning?',
    weight: 1.0,
    severityOnFailure: 'low',
    applicablePlatforms: ['all'],
    applicableContentTypes: ['all'],
    scope: ['prose'],
    isAutomated: true,
    isInformational: false,
    defaultStatus: 'PASS',
  },

  // ── Pillar 3: Audience Alignment ────────────────────────────────
  {
    ruleId: 'aud-1',
    pillarId: 'audience_alignment',
    label: 'Is this clearly written for one audience?',
    weight: 1.2,
    severityOnFailure: 'medium',
    applicablePlatforms: ['all'],
    applicableContentTypes: ['all'],
    scope: ['all'],
    isAutomated: false,
    isInformational: false,
    defaultStatus: 'MANUAL_REVIEW',
  },
  {
    ruleId: 'aud-2',
    pillarId: 'audience_alignment',
    label: 'Does it fulfill the purpose of searching & reading?',
    weight: 1.0,
    severityOnFailure: 'medium',
    applicablePlatforms: ['all'],
    applicableContentTypes: ['all'],
    scope: ['all'],
    isAutomated: true,
    isInformational: false,
    defaultStatus: 'PASS',
  },
  {
    ruleId: 'aud-3',
    pillarId: 'audience_alignment',
    label: 'Would this make them pause and read?',
    weight: 1.0,
    severityOnFailure: 'low',
    applicablePlatforms: ['all'],
    applicableContentTypes: ['all'],
    scope: ['all'],
    isAutomated: false,
    isInformational: false,
    defaultStatus: 'MANUAL_REVIEW',
  },

  // ── Pillar 4: E-E-A-T Check ──────────────────────────────────────
  {
    ruleId: 'eat-1',
    pillarId: 'eeat_check',
    label: 'Is lived experience, observation, or real context added?',
    weight: 1.4,
    severityOnFailure: 'high',
    applicablePlatforms: ['all'],
    applicableContentTypes: ['all'],
    scope: ['prose'],
    isAutomated: true,
    isInformational: false,
    defaultStatus: 'PASS',
  },
  {
    ruleId: 'eat-2',
    pillarId: 'eeat_check',
    label: 'Does the content explain why or how, not just what?',
    weight: 1.2,
    severityOnFailure: 'medium',
    applicablePlatforms: ['all'],
    applicableContentTypes: ['all'],
    scope: ['prose'],
    isAutomated: true,
    isInformational: false,
    defaultStatus: 'PASS',
  },
  {
    ruleId: 'eat-3',
    pillarId: 'eeat_check',
    label: 'Does it show you are a thought-leader in this niche?',
    weight: 1.0,
    severityOnFailure: 'medium',
    applicablePlatforms: ['all'],
    applicableContentTypes: ['all'],
    scope: ['all'],
    isAutomated: false,
    isInformational: false,
    defaultStatus: 'MANUAL_REVIEW',
  },

  // ── Pillar 5: Insight First ─────────────────────────────────────
  {
    ruleId: 'ins-1',
    pillarId: 'insight_first',
    label: 'Does the content start with an insight, observation, or hook, and not a long setup?',
    weight: 1.5,
    severityOnFailure: 'high',
    applicablePlatforms: ['all'],
    applicableContentTypes: ['all'],
    scope: ['prose'],
    isAutomated: true,
    isInformational: false,
    defaultStatus: 'PASS',
  },
  {
    ruleId: 'ins-2',
    pillarId: 'insight_first',
    label: 'Does it immediately come to the point?',
    weight: 1.2,
    severityOnFailure: 'medium',
    applicablePlatforms: ['all'],
    applicableContentTypes: ['all'],
    scope: ['prose'],
    isAutomated: true,
    isInformational: false,
    defaultStatus: 'PASS',
  },

  // ── Pillar 6: Meaning & Crispness Test ──────────────────────────
  {
    ruleId: 'mc-1',
    pillarId: 'meaning_crispness',
    label: 'Every line adds new or valuable info, clarity, or perspective for that one audience.',
    weight: 1.2,
    severityOnFailure: 'medium',
    applicablePlatforms: ['all'],
    applicableContentTypes: ['all'],
    scope: ['prose'],
    isAutomated: false,
    isInformational: false,
    defaultStatus: 'MANUAL_REVIEW',
  },
  {
    ruleId: 'mc-2',
    pillarId: 'meaning_crispness',
    label: 'No filler lines. No "nice to have" sentences.',
    weight: 1.4,
    severityOnFailure: 'medium',
    applicablePlatforms: ['all'],
    applicableContentTypes: ['all'],
    scope: ['prose'],
    isAutomated: true,
    isInformational: false,
    defaultStatus: 'PASS',
  },

  // ── Pillar 7: Zero Offensiveness Rule ───────────────────────────
  {
    ruleId: 'off-1',
    pillarId: 'zero_offensiveness',
    label: 'Are we not undermining any profession, system, academy, or industry?',
    weight: 1.0,
    severityOnFailure: 'high',
    applicablePlatforms: ['all'],
    applicableContentTypes: ['all'],
    scope: ['all'],
    isAutomated: false,
    isInformational: false,
    defaultStatus: 'MANUAL_REVIEW',
  },
  {
    ruleId: 'off-2',
    pillarId: 'zero_offensiveness',
    label: 'Is it polished and respectful, even when talking about gaps or competitors?',
    weight: 1.0,
    severityOnFailure: 'medium',
    applicablePlatforms: ['all'],
    applicableContentTypes: ['all'],
    scope: ['all'],
    isAutomated: false,
    isInformational: false,
    defaultStatus: 'MANUAL_REVIEW',
  },

  // ── Pillar 8: Relevance to Brand Positioning ───────────────────
  {
    ruleId: 'bp-1',
    pillarId: 'brand_positioning',
    label: "Is the message aligned with the brand's voice?",
    weight: 1.0,
    severityOnFailure: 'medium',
    applicablePlatforms: ['all'],
    applicableContentTypes: ['all'],
    scope: ['all'],
    isAutomated: false,
    isInformational: false,
    defaultStatus: 'MANUAL_REVIEW',
  },
  {
    ruleId: 'bp-2',
    pillarId: 'brand_positioning',
    label: "Are we reinforcing authority, sharing the brand's experience & expertise without sounding salesy?",
    weight: 1.2,
    severityOnFailure: 'medium',
    applicablePlatforms: ['all'],
    applicableContentTypes: ['all'],
    scope: ['all'],
    isAutomated: true,
    isInformational: false,
    defaultStatus: 'PASS',
  },

  // ── Pillar 9: Structure Check ───────────────────────────────────
  {
    ruleId: 'str-1',
    pillarId: 'structure_check',
    label: 'Is the headline strong & USP-driven?',
    weight: 1.2,
    severityOnFailure: 'medium',
    applicablePlatforms: ['all'],
    applicableContentTypes: ['all'],
    scope: ['headings'],
    isAutomated: true,
    isInformational: false,
    defaultStatus: 'PASS',
  },
  {
    ruleId: 'str-2',
    pillarId: 'structure_check',
    label: 'Is the supporting line relevant?',
    weight: 1.0,
    severityOnFailure: 'low',
    applicablePlatforms: ['all'],
    applicableContentTypes: ['all'],
    scope: ['headings', 'prose'],
    isAutomated: true,
    isInformational: false,
    defaultStatus: 'PASS',
  },
  {
    ruleId: 'str-3',
    pillarId: 'structure_check',
    label: 'Is the flow logical and tight?',
    weight: 1.2,
    severityOnFailure: 'medium',
    applicablePlatforms: ['all'],
    applicableContentTypes: ['all'],
    scope: ['all'],
    isAutomated: true,
    isInformational: false,
    defaultStatus: 'PASS',
  },
  {
    ruleId: 'str-4',
    pillarId: 'structure_check',
    label: 'No unnecessary past tense unless necessary.',
    weight: 1.0,
    severityOnFailure: 'low',
    applicablePlatforms: ['all'],
    applicableContentTypes: ['all'],
    scope: ['prose'],
    isAutomated: true,
    isInformational: false,
    defaultStatus: 'PASS',
  },

  // ── Pillar 10: No Direct Sales Pitches ──────────────────────────
  {
    ruleId: 'sp-1',
    pillarId: 'no_direct_sales_pitches',
    label: 'Crisp storytelling without exaggeration.',
    weight: 1.2,
    severityOnFailure: 'medium',
    applicablePlatforms: ['all'],
    applicableContentTypes: ['all'],
    scope: ['prose'],
    isAutomated: true,
    isInformational: false,
    defaultStatus: 'PASS',
  },
  {
    ruleId: 'sp-2',
    pillarId: 'no_direct_sales_pitches',
    label: 'Professional, subtle drama.',
    weight: 1.0,
    severityOnFailure: 'low',
    applicablePlatforms: ['all'],
    applicableContentTypes: ['all'],
    scope: ['all'],
    isAutomated: false,
    isInformational: false,
    defaultStatus: 'MANUAL_REVIEW',
  },
  {
    ruleId: 'sp-3',
    pillarId: 'no_direct_sales_pitches',
    label: 'No self-promotion unless asked.',
    weight: 1.2,
    severityOnFailure: 'high',
    applicablePlatforms: ['all'],
    applicableContentTypes: ['all'],
    scope: ['prose', 'cta'],
    isAutomated: true,
    isInformational: false,
    defaultStatus: 'PASS',
  },
  {
    ruleId: 'sp-4',
    pillarId: 'no_direct_sales_pitches',
    label: 'No overemphasis on milestones (e.g., 10 years).',
    weight: 1.2,
    severityOnFailure: 'medium',
    applicablePlatforms: ['all'],
    applicableContentTypes: ['all'],
    scope: ['prose'],
    isAutomated: true,
    isInformational: false,
    defaultStatus: 'PASS',
  },

  // ── Pillar 11: Compliance & Risk Check ──────────────────────────
  {
    ruleId: 'comp-1',
    pillarId: 'compliance_risk',
    label: 'No claims that trigger compliance (e.g., pharma, medical).',
    weight: 1.5,
    severityOnFailure: 'critical',
    applicablePlatforms: ['all'],
    applicableContentTypes: ['all'],
    scope: ['prose', 'headings'],
    isAutomated: true,
    isInformational: false,
    defaultStatus: 'PASS',
  },
  {
    ruleId: 'comp-2',
    pillarId: 'compliance_risk',
    label: 'No overstatements for industries where neutrality matters (finance, telecom, etc.).',
    weight: 1.5,
    severityOnFailure: 'critical',
    applicablePlatforms: ['all'],
    applicableContentTypes: ['all'],
    scope: ['prose', 'headings'],
    isAutomated: true,
    isInformational: false,
    defaultStatus: 'PASS',
  },

  // ── Pillar 12: Visual + Platform Fit ────────────────────────────
  {
    ruleId: 'vpf-1',
    pillarId: 'visual_platform_fit',
    label: 'Does it suit the platform (Website, LinkedIn, newsletter, etc.)?',
    weight: 1.0,
    severityOnFailure: 'low',
    applicablePlatforms: ['all'],
    applicableContentTypes: ['all'],
    scope: ['all'],
    isAutomated: true,
    isInformational: false,
    defaultStatus: 'PASS',
  },
  {
    ruleId: 'vpf-2',
    pillarId: 'visual_platform_fit',
    label: 'Is it scannable (bullets, short paras, hooks)?',
    weight: 1.4,
    severityOnFailure: 'medium',
    applicablePlatforms: ['all'],
    applicableContentTypes: ['all'],
    scope: ['prose', 'bullet_list', 'numbered_list'],
    isAutomated: true,
    isInformational: false,
    defaultStatus: 'PASS',
  },
  {
    ruleId: 'vpf-3',
    pillarId: 'visual_platform_fit',
    label: 'Does it have enough media such as images, graphs, infographics, video embeds, etc.?',
    weight: 1.0,
    severityOnFailure: 'low',
    applicablePlatforms: ['all'],
    applicableContentTypes: ['all'],
    scope: ['all'],
    isAutomated: true,
    isInformational: true, // Recommended, does not fail content
    defaultStatus: 'PASS',
  },
]

/**
 * Filter catalog for active platform and content-type rules
 */
export function getApplicableRules(platform = 'website', contentType = 'blog') {
  return QA_RULES_CATALOG.filter((rule) => {
    const platformMatch =
      rule.applicablePlatforms.includes('all') ||
      rule.applicablePlatforms.includes(platform.toLowerCase())

    const contentMatch =
      rule.applicableContentTypes.includes('all') ||
      rule.applicableContentTypes.includes(contentType.toLowerCase())

    return platformMatch && contentMatch
  })
}

/**
 * Get map of ruleId -> rule definition
 */
export function getRulesMap() {
  const map = new Map()
  for (const rule of QA_RULES_CATALOG) {
    map.set(rule.ruleId, rule)
    map[rule.ruleId] = rule
  }
  return map
}
